### ISSUE TITLE
执行命令之后出现了这个错误，是图片太多了吗？

### ISSUE THREAD

**Issue by jayronlou** [JowayYoung/img-master#1]
❯ 处理图像总数：1595张
⠦ 图像正在压缩......undefined:2
<html><head>
^

SyntaxError: Unexpected token < in JSON at position 1
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/img-master/lib/compress.js:48:21)
    at IncomingMessage.emit (events.js:315:20)
    at IncomingMessage.Readable.read (internal/streams/readable.js:519:10)
    at flow (internal/streams/readable.js:992:34)
    at resume_ (internal/streams/readable.js:973:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)

**Comment by JowayYoung** [comment]
是的，图片太多了，被tinyimg网站监测出来了
